set -x
MODEL_PATH=/home/pengxy2024/rlhf/model/Qwen2.5-0.5B-Instruct
export VLLM_ATTENTION_BACKEND=XFORMERS
export WANDB_API_KEY=3794b1a3f5c1feef3ff49616c1ba75766abab13d
export CUDA_VISIBLE_DEVICES=1
export WANDB_MODE=offline
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=remax \
    data.train_files=data/kk \
    data.val_files=data/kk \
    data.train_batch_size=2 \
    data.val_batch_size=2 \
    data.max_prompt_length=400 \
    data.max_response_length=2048 \
    actor_rollout_ref.model.path=$MODEL_PATH\
    actor_rollout_ref.actor.optim.lr=3e-7 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    actor_rollout_ref.actor.ppo_micro_batch_size=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.grad_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=32 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['wandb'] \
    trainer.project_name='GRPO_logic_KK' \
    trainer.experiment_name='Qwen-0.5B-remax' \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.default_local_dir=../output/remax-0531 \
    trainer.default_hdfs_dir=null \
    trainer.save_freq=0 \
    trainer.test_freq=100 \
    trainer.total_epochs=1 $@ 2>&1 | tee grpo.log
